[package]
name = "day6"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitstring = "0.1.2"
float-cmp = "0.9.0"
itertools = "0.10.1"
ndarray = "0.15.4"
